---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.12.7'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      stages: [pre-commit]
      additional_dependencies:
        - tomli
      exclude: "docs/locales"
      args: [--write-changes]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [
          "--verbose",
          "--scope",
          "jose,oauth,oidc,client",
        ]
